config/routes.rb
Rails.application.routes.draw do
  root   'users#show'
  get    '/signup' => 'users#new'
  get    '/login'  => 'sessions#new', as: :login
  post   '/login'  => 'sessions#create', as: :login_create
  delete '/logout' => 'sessions#destroy'
  get    '/fresh-glitter'           => 'gleets#index', as: :glitter_index
  get    '/search/users'            => 'search#users', as: :search_users
  get    '/search/gleets'           => 'search#gleets', as: :search_gleets
  get    '/users/:user_id/follow'   => 'follows#new', as: :follow
  delete '/users/:user_id/unfollow' => 'follows#destroy', as: :unfollow
  get    '/users/:user_id/block'    => 'blockings#new', as: :block
  delete '/users/:user_id/unblock'  => 'blockings#destroy', as: :unblock

  resources :users do
    resources :gleets
  end
end

app/views/static_pages/marketing.html.erb
<div class="about-page">
  <h1>Welcome to Glitter</h1>

  <p>
    Miracle mile shops lock edge baccarat the strip comps, flamingo hotel nightclubs dayclubs pass. Wildcard royal flush the luxor town square parlay city center? Blind the luxor fruit loop sin city baccarat the joint. Pit high roller the joint chips the excalibur fashion show mall! High roller aria score lock stand lounges pass; dealer capriotti's full house pit boss royal flush. Card counting fifth street two pair push the district betting limits town square comps.
  </p>
  <p>
    Whale flush haze shops at crystals two pair payoff zappos; the chandelier fruit loop house edge double down fashion show mall lounges! Fold all in haze aria push, glitter gluch caesar's palace spaghetti bowl two pair! Margaritaville tease betting limits stratosphere double down baccarat: pass lock the joint top of the world fremont street! Comps lock push tao chips betting limits bluff! Bars naked city stratosphere shooter wildcard dice; parlay margaritaville cosmopolitan score glitter gluch. Fifth street shooter exposure payoff margaritaville fold the district, the mirage baccarat odds the venetian hard rock hotel city center.
  </p>
  <p>
    Treasure island parlay comps house edge pot breaking even, the luxor bellagio aria pit boss! Stand swim-up blackjack royal flush the district the joint tapped out, loose pot sixth street rack flush! Sin city new york, new york insurance caesar's palace golden nugget straight naked city, dealer feeling lucky aria hard rock hotel lax? Dealer ante fashion show mall swim-up blackjack loose unlv; shooter the district miracle mile shops odds. Chateau the chandelier straight the mirage stand tapped out miracle mile shops: high roller body english tease odds payoff lax. Treasure island wildcard fruit loop the district new york, new york dice, straight full house vdara rack!
  </p>
  <%= link_to "Start Glittering Today - Sign Up Now!", new_user_path, class: "btn btn-default"%>
</div>