config/routes.rb
Rails.application.routes.draw do
  root   'users#show'
  get    '/signup' => 'users#new'
  get    '/login'  => 'sessions#new', as: :login
  post   '/login'  => 'sessions#create', as: :login_create
  delete '/logout' => 'sessions#destroy'
  get    '/fresh-glitter'           => 'gleets#index', as: :glitter_index
  get    '/search/users'            => 'search#users', as: :search_users
  get    '/search/gleets'           => 'search#gleets', as: :search_gleets
  get    '/users/:user_id/follow'   => 'follows#new', as: :follow
  delete '/users/:user_id/unfollow' => 'follows#destroy', as: :unfollow
  get    '/users/:user_id/block'    => 'blockings#new', as: :block
  delete '/users/:user_id/unblock'  => 'blockings#destroy', as: :unblock

  resources :users do
    resources :gleets
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :gleets
  has_many :active_blocks, class_name:  "Blocking",
                           foreign_key: "blocker_id",
                           dependent:   :destroy
  has_many :passive_blocks, class_name: "Blocking",
                            foreign_key: "blocked_id",
                            dependent:  :destroy
  has_many :blocking, through: :active_blocks, source: :blocked
  has_many :blocked_by, through: :passive_blocks, source: :blocker
  acts_as_follower
  acts_as_followable
  acts_as_liker
  acts_as_likeable

  include PgSearch
  pg_search_scope :search, against: [:username, :email]

  before_validation :downcase_email
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :username, uniqueness: true,
                       length: { minimum: 5, too_short: "Username must be at least 5 characters",
                                 maximum: 25, too_long: "Username must be 25 characters or less" }
  validates :email, presence: true,
                    uniqueness: true,
                    case_sensitive: false
  validate :email_is_valid_format
  validates :password, presence: true,
                       length: { minimum: 6, too_short: "Password must be at least 6 characters" }
  validates :bio, presence: true

  before_save :set_default_picture


  def email_is_valid_format
    errors.add(:email, "Not a valid email address") unless self.email =~ VALID_EMAIL_REGEX
  end

  def blocking?(other_user)
    blocking.exists?(other_user)
  end

  def blocked_by?(other_user)
    blocked_by.exists?(other_user)
  end

  def block(other_user)
    active_blocks.create(blocked_id: other_user.id)
    unfollow!(other_user)
  end

  def unblock(other_user)
    active_blocks.find_by(blocked_id: other_user.id).destroy
  end

  def to_param
    username
  end

  private

  def downcase_email
    self.email = self.email.downcase if self.email.present?
  end

  def set_default_picture
    self.picture_url = picture_url.empty? ? "https://unsplash.it/400/?image=1061" : picture_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :disallow_user, only: [:new, :create]
  before_action :require_user, only: [:index]

  def index
    @users = User.order(:created_at).page(params[:page])
  end

  def show
    if current_user
      @user = params[:id] ? User.find_by(username: params[:id]) : current_user
      if not_me?
        @gleets = @user.gleets.order(created_at: :desc).page(params[:page])
      else
        @gleets = Gleet.timeline(@user).page(params[:page])
      end
    else
      redirect_to glitter_index_path
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to Glitter!"
      log_in @user
      redirect_to :root
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :name, :email, :password,
                                 :password_confirmation, :picture_url, :bio)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_bio.html.erb
<div class="user">
  <img src="<%= @user.picture_url %>" class="img-rounded avatar">
  <h3><%= @user.username %></h3>
  <div class="row">
    <div class="col-xs-4">
      <h6>GLEETS</h6>
      <h6><%= @user.gleets.count %></h6>
    </div>
    <div class="col-xs-4">
      <h6>FOLLOWING</h6>
      <h6><%= @user.followees(User).count %></h6>
    </div>
    <div class="col-xs-4">
      <h6>FOLLOWERS</h6>
      <h6><%= @user.followers(User).count%></h6>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 user-bio">
      <h4>User Bio:</h4>
      <%= simple_format @user.bio %>
    </div>
  </div>
</div>

app/views/users/_block_button.html.erb
<% if current_user.blocking?(user) %>
  <%= link_to "UnBlock User", unblock_path(user_id: user.id), method: :delete, class: "btn btn-default" %>
<% else %>
  <%= link_to "Block User", block_path(user_id: user.id), class: "btn btn-default" %>
<% end %>

app/views/users/_follow_button.html.erb
<% unless current_user.blocking?(user) %>
  <% if current_user.follows?(user) %>
    <%= link_to "UnFollow", unfollow_path(user_id: user.id), method: :delete, class: "btn btn-default btn-follow", id: "btn-follow", remote: true %>
  <% else %>
    <%= link_to "Follow", follow_path(user_id: user.id), class: "btn btn-default btn-follow", id: "btn-follow", remote: true %>
  <% end %>
<% end %>

app/views/users/_form.html.erb
<%= simple_form_for @user ||= User.new do |f| %>
  <%= f.input :username, autofocus: true %>
  <%= f.input :email %>
  <%= f.input :picture_url %>
  <%= f.input :bio %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.button :submit %>
<% end %>

app/views/users/_search.html.erb
<%= form_tag search_users_path, method: :get, class: "form-group" do %>
  <%= text_field_tag :query, params[:query], placeholder: "Search all users", class: "form-control" %>
  <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
<% end %>

app/views/users/_user.html.erb
<div class="gleet">
  <h4><%= link_to user.username, user, class: "user-link" %></h4>
  <div class="text-right user-buttons" id="user-buttons-<%= user.id %>">
    <%= render partial: 'users/follow_button', locals: { user: user } %>
    <%= render partial: 'users/block_button', locals: { user: user } %>
  </div>
</div>

app/views/users/_user_aside.html.erb
<div class="user">
  <%= link_to "#", data: { toggle: "modal", target: "#user_biography", remote: false } do %>
    <img src="<%= @user.picture_url %>" class="img-rounded avatar">
  <% end %>
  <h3><%= @user.username %></h3>
  <div class="row">
    <div class="col-xs-4">
      <h6>GLEETS</h6>
      <h6><%= @user.gleets.count %></h6>
    </div>
    <div class="col-xs-4">
      <h6>FOLLOWING</h6>
      <h6><%= @user.followees(User).count %></h6>
    </div>
    <div class="col-xs-4">
      <h6>FOLLOWERS</h6>
      <h6><%= @user.followers(User).count%></h6>
    </div>
  </div>
</div>
<% if not_me? %>
  <div class="full-width" id="user-buttons-<%= @user.id %>">
    <%= render partial: 'follow_button', locals: { user: @user } %>
    <%= render partial: 'block_button', locals: { user: @user } %>
  </div>
<% end %>

app/views/users/index.html.erb
<%= render partial: 'users/search' %>

<h2>All Users</h2>

<%= render @users %>

<%= paginate @users, :theme => 'twitter-bootstrap-3' %>

app/views/users/new.html.erb
<%= render partial: 'form' %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-4">
    <%= render partial: 'user_aside' %>
  </div>
  <div class="col-md-8">
    <%= render partial: 'gleets/form', locals: { user: @user, gleet: Gleet.new } unless not_me? %>
    <div id="gleets-list">
      <%= render @gleets %>
    </div>
    <%= paginate @gleets, :theme => 'twitter-bootstrap-3' %>
  </div>
</div>