config/routes.rb
Rails.application.routes.draw do
  root   'users#show'
  get    '/signup' => 'users#new'
  get    '/login'  => 'sessions#new', as: :login
  post   '/login'  => 'sessions#create', as: :login_create
  delete '/logout' => 'sessions#destroy'
  get    '/fresh-glitter'           => 'gleets#index', as: :glitter_index
  get    '/search/users'            => 'search#users', as: :search_users
  get    '/search/gleets'           => 'search#gleets', as: :search_gleets
  get    '/users/:user_id/follow'   => 'follows#new', as: :follow
  delete '/users/:user_id/unfollow' => 'follows#destroy', as: :unfollow
  get    '/users/:user_id/block'    => 'blockings#new', as: :block
  delete '/users/:user_id/unblock'  => 'blockings#destroy', as: :unblock

  resources :users do
    resources :gleets
  end
end

app/views/shared/_flashes.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

app/views/shared/_modal.html.erb
<div class="modal fade" id="<%= label %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><%= title %></h4>
      </div>
      <div class="modal-body">
        <%= yield %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_nav.html.erb
<ul class="list-inline text-right">
  <% if current_user %>
    <li><%= link_to "Users", users_path %></li>
    <li><%= link_to "New Gleet", new_user_gleet_path(user_id: current_user.id), data: { toggle: "modal", target: "#new_gleet_form", remote: false } %></li>
    <li><%= link_to "All Gleets", glitter_index_path %></li>
    <li><%= link_to "Profile", current_user %></li>
    <li><%= link_to "Log Out", "/logout", method: :delete, remote: true %></li>
  <% else %>
    <li><%= link_to "G", root_path, id: "logo" %></li>
    <li><%= link_to "Sign up", "/signup", data: { toggle: "modal", target: "#signup_form", remote: false } %></li>
    <li><%= link_to "Log In", "/login", data: { toggle: "modal", target: "#login_form", remote: false } %></li>
  <% end %>
</ul>