config/routes.rb
Rails.application.routes.draw do
  root   'users#show'
  get    '/signup' => 'users#new'
  get    '/login'  => 'sessions#new', as: :login
  post   '/login'  => 'sessions#create', as: :login_create
  delete '/logout' => 'sessions#destroy'
  get    '/fresh-glitter'           => 'gleets#index', as: :glitter_index
  get    '/search/users'            => 'search#users', as: :search_users
  get    '/search/gleets'           => 'search#gleets', as: :search_gleets
  get    '/users/:user_id/follow'   => 'follows#new', as: :follow
  delete '/users/:user_id/unfollow' => 'follows#destroy', as: :unfollow
  get    '/users/:user_id/block'    => 'blockings#new', as: :block
  delete '/users/:user_id/unblock'  => 'blockings#destroy', as: :unblock

  resources :users do
    resources :gleets
  end
end

app/models/gleet.rb
class Gleet < ActiveRecord::Base
  paginates_per 10
  belongs_to :user
  validates :body, presence: true
  validates :body, length: { maximum: 170, too_long: "%{count} characters is the maximum allowed" }

  before_save :sparkalize

  include PgSearch
  pg_search_scope :search, against: [:body]

  def self.timeline(user)
    following_ids = user.followees(User, pluck: :id)
    all_ids = following_ids << user.id
    where(user_id: all_ids).order(created_at: :desc)
  end

  def sparkalize
    txt = self.body
    txt.gsub!(/(ass)/i, 'sparkle')
    txt.gsub!(/(fag)/i, 'sparkle')
    txt.gsub!(/(shit)/i, 'sparkle')
    txt.gsub!(/(fuck)/i, 'sparkle')
    txt.gsub!(/(damn)/i, 'sparkle')
    txt.gsub!(/(crap)/i, 'sparkle')
    txt.gsub!(/(piss)/i, 'sparkle')
    txt.gsub!(/(dick)/i, 'sparkle')
    txt.gsub!(/(darn)/i, 'sparkle')
    txt.gsub!(/(cock)/i, 'sparkle')
    txt.gsub!(/(puss)/i, 'sparkle')
    txt.gsub!(/(slut)/i, 'sparkle')
    txt.gsub!(/(bitch)/i, 'sparkle')
    txt.gsub!(/(asshole)/i, 'sparkle')
    txt.gsub!(/(bastard)/i, 'sparkle')
  end
end

app/controllers/gleets_controller.rb
class GleetsController < ApplicationController
  before_action :require_user, only: [:new, :create, :destroy]

  def index
    @gleets = Gleet.order(:created_at => :desc).page(params[:page])
  end

  def new
    @gleet = Gleet.new
    @user = User.find(params[:user_id])
  end

  def create
    @this_gleet = Gleet.new(gleet_params)
    @this_gleet.user = current_user
    if @this_gleet.save
      flash[:success] = "A new Gleet shines in the sun!"
      respond_to do |format|
        format.html { redirect_to current_user }
        format.js {}
      end
    else
      flash[:warning] = "Please, glitter responsibly."
      redirect_to current_user
    end
  end

  def destroy
    gleet = Gleet.find(params[:id])
    gleet.destroy if gleet.user == current_user
    flash[:success] = "That Gleet has shined its last"
    redirect_to :back
  end

  private

  def gleet_params
    params.require(:gleet).permit(:body)
  end
end

app/helpers/gleets_helper.rb
module GleetsHelper
end

app/views/gleets/_form.html.erb
<%= simple_form_for [user, gleet], remote: true do |f| %>
  <%= f.input :body, label: false, placeholder: "What's sparklin' now?" %>
  <span id="counter"></span>
  <%= f.button :submit, "New Gleet", id: "btn-gleet" %>
<% end %>

app/views/gleets/_gleet.html.erb
<div class="gleet">
  <h6>
    <%= link_to gleet.user.username, gleet.user %>
    <span class="gleet-time"><%= gleet.created_at %></span>
    <% if current_user && current_user == gleet.user%>
      <%= link_to "Delete", user_gleet_path(gleet.user, gleet), method: :delete %>
    <% end %>
  </h6>
  <%= simple_format(gleet.body) %>
</div>

app/views/gleets/_search.html.erb
<%= form_tag search_gleets_path, method: :get, class: "form-group" do %>
  <%= text_field_tag :query, params[:query], placeholder: "Search all Gleets", class: "form-control" %>
  <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
<% end %>

app/views/gleets/create.js.erb
$('#new_gleet_form').modal('toggle')
$('#new_gleet')[0].reset()
$('#gleets-list').prepend('<%=j render @this_gleet %>')
$('#main').prepend('<%=j render "shared/flashes", flash: { success: "A new Gleet shines in the sun!" } %>')

app/views/gleets/index.html.erb
<%= render partial: 'gleets/search' %>

<h2>Most Recent Gleets</h2>

<div class="gleets" id="gleets-list">
  <%= render @gleets %>
</div>

<%= paginate @gleets, :theme => 'twitter-bootstrap-3' %>

app/views/gleets/new.html.erb
<h1>New Gleet</h1>

<%= render partial: 'form', locals: { gleet: @gleet, user: @user } %>

<%= link_to "Home", root_path, class: "btn btn-default" %>